### ISSUE TITLE
grimoirelab-gitee deployment error

### ISSUE THREAD

**Issue by chentingting16** [grimoirelab-gitee/grimoirelab-perceval-gitee#16]
你好，我参考https://github.com/grimoirelab-gitee/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F  部署grimoirelab gitee。前两步已经完成，并已经验证成功。
在进行第三步构建代码时，我发现releases路径下没有latest，如下图
![image](https://user-images.githubusercontent.com/42869208/224220994-6285224b-94b4-4cdb-b24f-0b8b311ae926.png)

然后我选择了一个旧版本，将红圈部分改为/releases/old/0.3.0进行构建,
（我额外创建了/root/tmp/log文件和/root/ivenv、repos文件夹）
文件目录如下:
/root/tmp/log
/root/ivenv
/root/repos
/root/grimoirelab
执行的命令如下：
`sudo ./build_grimoirelab -l debug --logfile /root/tmp/log --build --install --check \
  --relfile ../releases/old/0.3.0 --reposdir /root/repos \
 --install_venv /root/ivenv`

然后出现以下错误：
```Checking installable (all modules at once)...OK
Checking installable (grimoirelab)...OK
Checking installable (grimoirelab-toolkit)...OK
Checking installable (perceval)...OK
Checking run (perceval)...OK
Checking installable (perceval-mozilla)...OK
Checking run (perceval-mozilla)...OK
Checking installable (perceval-opnfv)...OK
Checking run (perceval-opnfv)...OK
Checking installable (perceval-puppet)...OK
Checking run (perceval-puppet)...OK
Checking installable (perceval-weblate)...OK
Checking run (perceval-weblate)...OK
Checking installable (kingarthur)...OK
Checking run (kingarthur)...OK
Checking installable (grimoire-elk)...OK
Checking run (grimoire-elk)...Traceback (most recent call last):
  File "./build_grimoirelab", line 961, in <module>
    main()
  File "./build_grimoirelab", line 947, in main
    checker.check_built()
  File "./build_grimoirelab", line 757, in check_built
    self.check_run(venv, module)
  File "./build_grimoirelab", line 800, in check_run
    (success, output) = venv.run_command(command, exit=False)
  File "./build_grimoirelab", line 425, in run_command
    (success, output) = super().run_command(new_args, cwd=cwd,
  File "./build_grimoirelab", line 289, in run_command
    result = subprocess.run(args, cwd=cwd,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmplrtl39nu/bin/p2o.py'```



请问这怎么解决哇？感谢！

**Comment by eyehwan** [comment]
你好， 我们这个代码仓已经不再使用，请使用https://github.com/open-metrics-code/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F 参考，来搭建环境。 

https://github.com/open-metrics-code/grimoirelab/tree/master/releases 在这里 是有latest。

**Comment by chentingting16** [comment]
邮件已经收到！陈婷婷College of Computer Science, Sichuan UniversityChengdu, 610065Sichuan Province. P.R. ChinaTEL:13258139559

**Comment by chentingting16** [comment]
嗯嗯，我现在已经使用了新的代码仓库，但是还是出现以上错误。

**Comment by chentingting16** [comment]
```
GrimoireLab release: 0.3.0
Building...

Built module grimoirelab: OK
Built module grimoirelab-toolkit: OK
Built module perceval: OK
Built module perceval-mozilla: OK
Built module perceval-opnfv: OK
Built module perceval-puppet: OK
Built module perceval-weblate: OK
Built module kingarthur: OK
Built module grimoire-elk: OK
Built module sortinghat: OK
Built module kidash: OK
Built module grimoirelab-panels: OK
Built module sirmordred: OK
Built module cereslib: OK
Built module graal: OK
Installing...
Installed modules: grimoirelab,grimoirelab-toolkit,perceval,perceval-mozilla,perceval-opnfv,perceval-puppet,perceval-weblate,kingarthur,grimoire-elk,sortinghat,kidash,grimoirelab-panels,sirmordred,cereslib,graal
Checking...
Checking versions...
Checked version for grimoirelab: OK
Checked version for grimoirelab-toolkit: OK
Checked version for perceval: OK
Checked version for perceval-mozilla: Fail
Checked version for perceval-opnfv: Fail
Checked version for perceval-puppet: Fail
Checked version for perceval-weblate: Fail
Checked version for kingarthur: OK
Checked version for grimoire-elk: OK
Checked version for sortinghat: OK
Checked version for kidash: OK
Checked version for grimoirelab-panels: OK
Checked version for sirmordred: OK
Checked version for cereslib: OK
Checked version for graal: OK
Checking installable (all modules at once)...OK
Checking installable (grimoirelab)...OK
Checking installable (grimoirelab-toolkit)...OK
Checking installable (perceval)...OK
Checking run (perceval)...OK
Checking installable (perceval-mozilla)...OK
Checking run (perceval-mozilla)...OK
Checking installable (perceval-opnfv)...OK
Checking run (perceval-opnfv)...OK
Checking installable (perceval-puppet)...OK
Checking run (perceval-puppet)...OK
Checking installable (perceval-weblate)...OK
Checking run (perceval-weblate)...OK
Checking installable (kingarthur)...OK
Checking run (kingarthur)...OK
Checking installable (grimoire-elk)...OK
Checking run (grimoire-elk)...Traceback (most recent call last):
  File "./build_grimoirelab", line 961, in <module>
    main()
  File "./build_grimoirelab", line 947, in main
    checker.check_built()
  File "./build_grimoirelab", line 757, in check_built
    self.check_run(venv, module)
  File "./build_grimoirelab", line 800, in check_run
    (success, output) = venv.run_command(command, exit=False)
  File "./build_grimoirelab", line 425, in run_command
    (success, output) = super().run_command(new_args, cwd=cwd,
  File "./build_grimoirelab", line 289, in run_command
    result = subprocess.run(args, cwd=cwd,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwbbzfz6q/bin/p2o.py'
```

**Comment by chentingting16** [comment]
谢谢~我已使用了新的仓库和参考说明，在第三步build时，还是出现了以上的错误。
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmplrtl39nu/bin/p2o.py'
我查了下类似的问题解决方案，是不是grimoire-elk有语法错误哇？
https://blog.csdn.net/suiyingy/article/details/125552055

可以帮我看看嘛？非常感谢！ @eyehwan

**Comment by eyehwan** [comment]
是否已把/tmp 目录清理干净？

**Comment by chentingting16** [comment]
是的已经清除干净了。
非常感谢您的帮助！在另一个仓库的issue中发现了同样的问题，目前已解决。
![image](https://user-images.githubusercontent.com/42869208/224459293-ef8136a6-1544-4d11-8566-17abe5630a68.png)
https://github.com/chaoss/grimoirelab/issues/512

**Comment by eyehwan** [comment]
Thank you so much @chentingting16 , we will update the build file. @lishengbao , please update it. 
By the way,  are you interested in more discussion around metrics model design? 
We just release OSS-Compass which depend on Grimoirelab, to build metrics model to analysis community health. https://oss-compass.org/docs/zh/community/wechat/
If you joined with us, it would be great!
